import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const links = []


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Noticias de la API</title>
      </head>
      <body className={inter.className}>
        <header>
    
        <nav>
          <ul>
            {links.map(({label,route})=>(
              <li key={route}>
                <Link href={route}>
                {label}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        
        {children}
        </header>
        </body>
        
    </html>
  );
}
